/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// This file provides a simple key-value interface for storing Figma Make data using Deno KV.

// Get the Deno KV instance
const getKv = async () => {
  return await Deno.openKv();
};

// Set stores a key-value pair in the KV store.
export const set = async (key: string, value: any): Promise<void> => {
  const kv = await getKv();
  await kv.set([key], value);
};

// Get retrieves a key-value pair from the KV store.
export const get = async (key: string): Promise<any> => {
  const kv = await getKv();
  const result = await kv.get([key]);
  return result.value;
};

// Delete deletes a key-value pair from the KV store.
export const del = async (key: string): Promise<void> => {
  const kv = await getKv();
  await kv.delete([key]);
};

// Sets multiple key-value pairs in the KV store.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const kv = await getKv();
  const atomic = kv.atomic();
  for (let i = 0; i < keys.length; i++) {
    atomic.set([keys[i]], values[i]);
  }
  await atomic.commit();
};

// Gets multiple key-value pairs from the KV store.
export const mget = async (keys: string[]): Promise<any[]> => {
  const kv = await getKv();
  const results = await Promise.all(keys.map(k => kv.get([k])));
  return results.map(r => r.value);
};

// Deletes multiple key-value pairs from the KV store.
export const mdel = async (keys: string[]): Promise<void> => {
  const kv = await getKv();
  const atomic = kv.atomic();
  for (const key of keys) {
    atomic.delete([key]);
  }
  await atomic.commit();
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const kv = await getKv();
  const results = [];
  for await (const entry of kv.list({ prefix: [prefix] })) {
    results.push(entry.value);
  }
  return results;
};